name=input("Enter your name :")
branch=input("Enter your branch :")
gender=input("Enter your gender :")
college=input("Enter your college :")
age=int(input("Enter your age :"))
print('Name:',name)
print('Age:',age)
print('Gender:',gender)
print('College',college)
print('Branch:',branch)
